\documentclass[a4paper, 10pt]{report}
\usepackage{cmap}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{url}
\usepackage{caption}

\usepackage{graphicx}
\usepackage{tikz}
\usetikzlibrary{decorations,arrows,shapes}
\usepackage[margin=0.9in]{geometry}
\usepackage{url}
\usepackage{hyperref}
\usepackage{listings}
\usepackage{xspace}
\usepackage{tabularx}
\usepackage{makeidx}\makeindex
%\usepackage[numbers]{natbib}
\usepackage{natbib}
\bibliographystyle{plainnat}
\usepackage{algorithmic} 
\usepackage{algorithm}
%\usepackage[left=3cm,right=3cm,top=2cm,bottom=2cm]{geometry}
\usepackage{amsmath,amsthm,amsfonts,amssymb}
\setlength{\parindent}{0mm}
\setlength{\parskip}{1mm}
\newcommand{\commentout}[1]{}
\renewcommand{\theequation}{\thesection.\arabic{\equation}}
\numberwithin{equation}{section}

\theoremstyle{definition}
\newtheorem{Def}{Definition}[section]
\newtheorem{Rem}[Def]{Remark}
\newtheorem{RemDef}[Def]{Remark und Definition}
\newtheorem{DefRem}[Def]{Definition und Remark}
\newtheorem{Example}[Def]{Example}
\theoremstyle{plain}
\newtheorem{Theorem}[Def]{Theorem}
\newtheorem{DefTheorem}[Def]{Definition and Theorem}
\newtheorem{Corollary}[Def]{Corollary}
\newtheorem{Lemma}[Def]{Lemma}

\newcommand{\C}{\ensuremath{\mathbb{C}}\xspace}
\newcommand{\R}{\ensuremath{\mathbb{R}}\xspace}
\newcommand{\Q}{\ensuremath{\mathbb{Q}}\xspace}
\newcommand{\Z}{\ensuremath{\mathbb{Z}}\xspace}
\newcommand{\NN}{\ensuremath{\mathbb{N}_0}\xspace}
\newcommand{\N}{\ensuremath{\mathbb{N}}\xspace}
\newcommand{\sF}{\ensuremath{\mathcal{F}}\xspace}
\newcommand{\sN}{\ensuremath{\mathcal{N}}\xspace}
\newcommand{\Pot}{\ensuremath{\mathfrak{Pot}}\xspace}
\newcommand{\kronecker}{\raisebox{1pt}{\ensuremath{\:\otimes\:}}}

\DeclareMathOperator{\range}{range}

\newcommand{\skp}[1]{\left\langle#1\right\rangle}

\renewcommand{\epsilon}{\varepsilon}
\renewcommand{\phi}{\varphi}
\newcommand{\id}{\text{id}}

\newenvironment{Proof}{\par\noindent\upshape\textit{Proof. }\nopagebreak}{\qed\par}

\usepackage{setspace}
\onehalfspacing

\begin{document}

% \VignetteEngine{knitr::knitr}
% \VignetteIndexEntry{A Graphical Approach to Weighted Multiple Test Procedures}
% \VignetteDepends{coin}

\title{gMCP - an R package for a graphical approach to weighted multiple test procedures} 

%\author{Kornelius Rohmeyer}

%\maketitle\thispagestyle{empty}\vspace*{1cm}

<<OptionsAndLibraries, include=FALSE, message=FALSE>>=
# knitr has to be loaded for 'set_parent' and CRAN checks and also for opt_chunk during build process.
library(knitr)
if (exists("opts_chunk")) {
  opts_chunk$set(concordance=TRUE)
  opts_chunk$set(tidy.opts=list(keep.blank.line=FALSE, width.cutoff=95))
  opts_chunk$set(size="footnotesize")
  opts_chunk$set(cache=TRUE)
  opts_chunk$set(autodep=TRUE)
}
library(gMCP, quietly=TRUE)
options(width=140)
options(digits=4)
gMCPReport <- function(...) {invisible(NULL)}
graphGUI <- function(...) {invisible(NULL)}
#options(prompt="> ", continue="+ ")

@

\section*{Algorithm:}

Need function $p[[i]]:\;\R\rightarrow [0,1]$ (continuous and growing). We first consider the simple case of independent $Z$-tests.

<<>>=
m <- 3
theta <- rep(0, m)
s <- rep(1, m)

p <- list()
for (i in 1:m) {
  p[[i]] <- function(mu) {(1-pnorm((theta[i]-mu)/s[i])) }
}
@

<<fig.width=5.5, fig.height=5.5, out.width=".5\\linewidth", out.height=".5\\linewidth", fig.align="center", echo=FALSE>>=
plot(p[[1]], xlim=c(-3,3))
@

Then we need the function $V[[j]]:\;\R^m\rightarrow [0,1]$ (continuous and component-wise non-decreasing), which we get in the following way:

We start with a graph $G$.

<<>>=

library(gMCP)
G <- BonferroniHolm(3)

@


<<echo=FALSE, results='asis'>>=

cat(graph2latex(G, fig=FALSE, scaleText=TRUE, scale=0.7, fig.caption="Bonferroni-Holm"))

@

For a given $\mu\in\R^m$ we create a graph $G^{(\mu)}_0$ in the following way:

\begin{enumerate}
  \item For all $j$ with $\mu_j \leq 0$
    \begin{itemize}
      \item remove all edges starting in $H_j^0$
      \item replace $H_j^0$ through $H_j^{\mu_j}$
    \end{itemize}
  \item For all $j$ with $\mu_j > 0$
    \begin{itemize}
      \item
      \item
      \item
    \end{itemize}
\end{enumerate}

<<>>=

mu <- c(-1, 1, 2)



@


\end{document}
